pimcore:
    documents:
        web_to_print:
            enableInDefaultView: true
            generalTool: headlesschrome
            generalDocumentSaveMode: cleanup
            pdfreactorProtocol: null
            pdfreactorServer: localhost
            pdfreactorServerPort: '9423'
            pdfreactorBaseUrl: 'http://my.domain.com'
            pdfreactorApiKey: ''
            pdfreactorLicence: ''
            pdfreactorEnableLenientHttpsMode: false
            pdfreactorEnableDebugMode: false
            wkhtmltopdfBin: wkhtmltopdf
            wkhtml2pdfOptions:
                print-media-type: ''
                page-size: A4
            wkhtml2pdfHostname: 'http://demo.pimcore.org'
            headlessChromeSettings: "              'landscape' => false,\n                'printBackground' => true,\n                'displayHeaderFooter' => true,\n                'headerTemplate' => '\n                    <style>\n                        div{\n                        color: #F0F;\n                        font-size:15px !important\n                    }\n                    </style>\n                    <div class=\"pageNumber\"></div>/<div class=\"totalPages \"></div>\n                    <div>I am a header </div>\n                ' ,\n                'footerTemplate' => '<div style=\"font-size:10px !important;\">I am a footer</div>',\n                'margin' => ['top' => '10mm', 'bottom' => '40px', 'left' => '40px', 'right' => '40px']\n"
